### ISSUE TITLE
Does not run on Ubuntu 14.04

### ISSUE THREAD

**Issue by probonopd** [dino-/photoname#1]
Does not run on Ubuntu 14.04:

![](https://github.com/AppImage/appimage.github.io/blob/0aefde0985e6958c250bf531dbaec151ea660b5c/database/photoname/screenshot.png?raw=true)

Reference:
https://github.com/AppImage/appimage.github.io/pull/865

**Comment by dino-** [comment]
Release 'photoname v3.4' has been updated with a replacement AppImage built on a system running Ubuntu 14.04.5. Thank you for checking this!

**Comment by probonopd** [comment]
Thank you, works for me now.
